Feature/te 7272/master remove silex usage from tests
spryker-sdk/spryk-gui pull request #30
Opened 2020-09-09 14:48 UTC by asaulenko

- Developer(s): @asaulenko

- Ticket: https://spryker.atlassian.net/browse/TE-7272

- Academy PR: ACADEMY_URL_HERE

- Release Group: URL_HERE

- PR Overview: https://release.spryker.com/core/TE-7272 [Replace with actual PR overview link]

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   SprykGui           | minor                 |                       |

-----------------------------------------

#### Module Acl

##### Change log

Improvements

- Removed `\SprykerTest\Shared\Testify\Helper\ZedBootstrap` from tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.
- Added `\SprykerTest\Zed\Testify\Helper\Business\BusinessHelper` to tests.

2020-09-10 04:20 UTC, stereomon commented
I think this should be released as a patch as the only relevant change for projects here is the array access fix for the container.

The changelog information is too detailed and contains only the changes made to tests which are not relevant for the projects.

2020-09-10 07:32 UTC, gechetspr approved these changes

2020-09-10 07:32 UTC, gechetspr commented
Please remove actual test mentioning from the changelogs. For tests only helpers are relevant

2020-09-10 10:45 UTC, stereomon approved these changes

2020-09-10 10:46 UTC, stereomon requested changes
You only need to mention the array access update in your changelogs. Tests are not relevant to the projects.

2020-09-11 05:32 UTC, stereomon approved these changes

2020-09-17 10:16 UTC, merged